spring.application.name=search-service
server.port=${SERVER_PORT:8085}

spring.data.mongodb.uri=${SEARCH_MONGODB_URI:mongodb://localhost:27017/search-service}
spring.data.mongodb.uuid-representation=standard

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER_URI:http://localhost:8081}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_JWK_SET_URI:${AUTH_ISSUER_URI:http://localhost:8081}/.well-known/jwks.json}
