spring.application.name=payment-service
server.port=8082

spring.datasource.url=${PAYMENT_DB_URL:jdbc:mysql://localhost:3306/payment_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${PAYMENT_DB_USERNAME:root}
spring.datasource.password=${PAYMENT_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
